Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/usr/local/lib/python3.8/site-packages/nbclient/client.py", line 1265, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/usr/local/lib/python3.8/site-packages/jupyter_core/utils/__init__.py", line 160, in wrapped
    return loop.run_until_complete(inner)
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.8/site-packages/nbclient/client.py", line 703, in async_execute
    await self.async_execute_cell(
  File "/usr/local/lib/python3.8/site-packages/nbclient/client.py", line 1021, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/usr/local/lib/python3.8/site-packages/nbclient/client.py", line 915, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
sns.countplot(titanic['sex'], hue = titanic['survived'])
------------------

[0;31m------------------------------------------------------[0m
[0;31mValueError[0m           Traceback (most recent call last)
Cell [0;32mIn[5], line 1[0m
[0;32m----> 1[0m [43msns[49m[38;5;241;43m.[39;49m[43mcountplot[49m[43m([49m[43mtitanic[49m[43m[[49m[38;5;124;43m'[39;49m[38;5;124;43msex[39;49m[38;5;124;43m'[39;49m[43m][49m[43m,[49m[43m [49m[43mhue[49m[43m [49m[38;5;241;43m=[39;49m[43m [49m[43mtitanic[49m[43m[[49m[38;5;124;43m'[39;49m[38;5;124;43msurvived[39;49m[38;5;124;43m'[39;49m[43m][49m[43m)[49m

File [0;32m/usr/local/lib/python3.8/site-packages/seaborn/categorical.py:2943[0m, in [0;36mcountplot[0;34m(data, x, y, hue, order, hue_order, orient, color, palette, saturation, width, dodge, ax, **kwargs)[0m
[1;32m   2940[0m [38;5;28;01melif[39;00m x [38;5;129;01mis[39;00m [38;5;129;01mnot[39;00m [38;5;28;01mNone[39;00m [38;5;129;01mand[39;00m y [38;5;129;01mis[39;00m [38;5;129;01mnot[39;00m [38;5;28;01mNone[39;00m:
[1;32m   2941[0m     [38;5;28;01mraise[39;00m [38;5;167;01mValueError[39;00m([38;5;124m"[39m[38;5;124mCannot pass values for both `x` and `y`[39m[38;5;124m"[39m)
[0;32m-> 2943[0m plotter [38;5;241m=[39m [43m_CountPlotter[49m[43m([49m
[1;32m   2944[0m [43m    [49m[43mx[49m[43m,[49m[43m [49m[43my[49m[43m,[49m[43m [49m[43mhue[49m[43m,[49m[43m [49m[43mdata[49m[43m,[49m[43m [49m[43morder[49m[43m,[49m[43m [49m[43mhue_order[49m[43m,[49m
[1;32m   2945[0m [43m    [49m[43mestimator[49m[43m,[49m[43m [49m[43merrorbar[49m[43m,[49m[43m [49m[43mn_boot[49m[43m,[49m[43m [49m[43munits[49m[43m,[49m[43m [49m[43mseed[49m[43m,[49m
[1;32m   2946[0m [43m    [49m[43morient[49m[43m,[49m[43m [49m[43mcolor[49m[43m,[49m[43m [49m[43mpalette[49m[43m,[49m[43m [49m[43msaturation[49m[43m,[49m
[1;32m   2947[0m [43m    [49m[43mwidth[49m[43m,[49m[43m [49m[43merrcolor[49m[43m,[49m[43m [49m[43merrwidth[49m[43m,[49m[43m [49m[43mcapsize[49m[43m,[49m[43m [49m[43mdodge[49m
[1;32m   2948[0m [43m[49m[43m)[49m
[1;32m   2950[0m plotter[38;5;241m.[39mvalue_label [38;5;241m=[39m [38;5;124m"[39m[38;5;124mcount[39m[38;5;124m"[39m
[1;32m   2952[0m [38;5;28;01mif[39;00m ax [38;5;129;01mis[39;00m [38;5;28;01mNone[39;00m:

File [0;32m/usr/local/lib/python3.8/site-packages/seaborn/categorical.py:1530[0m, in [0;36m_BarPlotter.__init__[0;34m(self, x, y, hue, data, order, hue_order, estimator, errorbar, n_boot, units, seed, orient, color, palette, saturation, width, errcolor, errwidth, capsize, dodge)[0m
[1;32m   1525[0m [38;5;28;01mdef[39;00m [38;5;21m__init__[39m([38;5;28mself[39m, x, y, hue, data, order, hue_order,
[1;32m   1526[0m              estimator, errorbar, n_boot, units, seed,
[1;32m   1527[0m              orient, color, palette, saturation, width,
[1;32m   1528[0m              errcolor, errwidth, capsize, dodge):
[1;32m   1529[0m     [38;5;124;03m"""Initialize the plotter."""[39;00m
[0;32m-> 1530[0m     [38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43mestablish_variables[49m[43m([49m[43mx[49m[43m,[49m[43m [49m[43my[49m[43m,[49m[43m [49m[43mhue[49m[43m,[49m[43m [49m[43mdata[49m[43m,[49m[43m [49m[43morient[49m[43m,[49m
[1;32m   1531[0m [43m                             [49m[43morder[49m[43m,[49m[43m [49m[43mhue_order[49m[43m,[49m[43m [49m[43munits[49m[43m)[49m
[1;32m   1532[0m     [38;5;28mself[39m[38;5;241m.[39mestablish_colors(color, palette, saturation)
[1;32m   1533[0m     [38;5;28mself[39m[38;5;241m.[39mestimate_statistic(estimator, errorbar, n_boot, seed)

File [0;32m/usr/local/lib/python3.8/site-packages/seaborn/categorical.py:437[0m, in [0;36m_CategoricalPlotter.establish_variables[0;34m(self, x, y, hue, data, orient, order, hue_order, units)[0m
[1;32m    435[0m [38;5;28;01mif[39;00m hue [38;5;129;01mis[39;00m [38;5;129;01mnot[39;00m [38;5;28;01mNone[39;00m:
[1;32m    436[0m     error [38;5;241m=[39m [38;5;124m"[39m[38;5;124mCannot use `hue` without `x` and `y`[39m[38;5;124m"[39m
[0;32m--> 437[0m     [38;5;28;01mraise[39;00m [38;5;167;01mValueError[39;00m(error)
[1;32m    439[0m [38;5;66;03m# No hue grouping with wide inputs[39;00m
[1;32m    440[0m plot_hues [38;5;241m=[39m [38;5;28;01mNone[39;00m

[0;31mValueError[0m: Cannot use `hue` without `x` and `y`
ValueError: Cannot use `hue` without `x` and `y`

